export const saveText = (text: string, filename: string) => {
  var a = document.createElement('a');
  a.setAttribute(
    'href',
    'data:text/plain;charset=utf-u,' + encodeURIComponent(text)
  );
  a.setAttribute('download', filename);
  a.click();
};

export const catalogItems = [
  {
    images: [
      'assets/img/promotion/promotion-29.jpg',
      'assets/img/promotion/promotion-15.jpg',
      'assets/img/promotion/promotion-9.jpg',
      'assets/img/promotion/promotion-8.jpg',
      'assets/img/promotion/promotion-14.jpg',
      'assets/img/promotion/promotion-28.jpg',
      'assets/img/promotion/promotion-16.jpg',
      'assets/img/promotion/promotion-17.jpg',
      'assets/img/promotion/promotion-13.jpg',
      'assets/img/promotion/promotion-12.jpg',
      'assets/img/promotion/promotion-10.jpg',
      'assets/img/promotion/promotion-38.jpg',
      'assets/img/promotion/promotion-39.jpg',
      'assets/img/promotion/promotion-11.jpg',
      'assets/img/promotion/promotion-43.jpg',
      'assets/img/promotion/promotion-42.jpg',
      'assets/img/promotion/promotion-40.jpg',
      'assets/img/promotion/promotion-41.jpg',
      'assets/img/promotion/promotion-44.jpg',
      'assets/img/promotion/promotion-20.jpg',
      'assets/img/promotion/promotion-34.jpg',
      'assets/img/promotion/promotion-1.jpg',
      'assets/img/promotion/promotion-35.jpg',
      'assets/img/promotion/promotion-21.jpg',
      'assets/img/promotion/promotion-37.jpg',
      'assets/img/promotion/promotion-23.jpg',
      'assets/img/promotion/promotion-3.jpg',
      'assets/img/promotion/promotion-2.jpg',
      'assets/img/promotion/promotion-22.jpg',
      'assets/img/promotion/promotion-36.jpg',
      'assets/img/promotion/promotion-32.jpg',
      'assets/img/promotion/promotion-26.jpg',
      'assets/img/promotion/promotion-6.jpg',
      'assets/img/promotion/promotion-7.jpg',
      'assets/img/promotion/promotion-27.jpg',
      'assets/img/promotion/promotion-33.jpg',
      'assets/img/promotion/promotion-25.jpg',
      'assets/img/promotion/promotion-31.jpg',
      'assets/img/promotion/promotion-19.jpg',
      'assets/img/promotion/promotion-5.jpg',
      'assets/img/promotion/promotion-4.jpg',
      'assets/img/promotion/promotion-18.jpg',
      'assets/img/promotion/promotion-30.jpg',
      'assets/img/promotion/promotion-24.jpg'
    ],
    catalog: 'promotion',
    name: 'promotion'
  },
  {
    images: [
      'assets/img/huthucphammatsu/huthucphammatsu-1.jpg',
      'assets/img/huthucphammatsu/huthucphammatsu-3.jpg',
      'assets/img/huthucphammatsu/huthucphammatsu-2.jpg',
      'assets/img/huthucphammatsu/huthucphammatsu-6.jpg',
      'assets/img/huthucphammatsu/huthucphammatsu-5.jpg',
      'assets/img/huthucphammatsu/huthucphammatsu-4.jpg'
    ],
    catalog: 'huthucphammatsu',
    name: 'huthucphammatsu'
  },
  {
    images: [
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-15.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-3.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-2.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-14.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-6.jpeg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-16.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-1.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-17.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-13.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-5.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-4.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-12.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-10.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-7.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-11.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-20.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-21.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-23.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-9.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-8.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-22.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-19.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-24.jpg',
      'assets/img/binhchainuocsuoi/binhchainuocsuoi-18.jpg'
    ],
    catalog: 'binhchainuocsuoi',
    name: 'binhchainuocsuoi'
  },
  {
    images: [
      'assets/img/hopthucphampp/hopthucphampp-18.jpg',
      'assets/img/hopthucphampp/hopthucphampp-19.jpg',
      'assets/img/hopthucphampp/hopthucphampp-20.jpg',
      'assets/img/hopthucphampp/hopthucphampp-8.jpg',
      'assets/img/hopthucphampp/hopthucphampp-9.jpg',
      'assets/img/hopthucphampp/hopthucphampp-2.jpg',
      'assets/img/hopthucphampp/hopthucphampp-3.jpg',
      'assets/img/hopthucphampp/hopthucphampp-1.jpg',
      'assets/img/hopthucphampp/hopthucphampp-4.jpg',
      'assets/img/hopthucphampp/hopthucphampp-5.jpg',
      'assets/img/hopthucphampp/hopthucphampp-7.jpg',
      'assets/img/hopthucphampp/hopthucphampp-6.jpg',
      'assets/img/hopthucphampp/hopthucphampp-12.jpg',
      'assets/img/hopthucphampp/hopthucphampp-13.jpg',
      'assets/img/hopthucphampp/hopthucphampp-11.jpg',
      'assets/img/hopthucphampp/hopthucphampp-10.jpg',
      'assets/img/hopthucphampp/hopthucphampp-14.jpg',
      'assets/img/hopthucphampp/hopthucphampp-15.jpg',
      'assets/img/hopthucphampp/hopthucphampp-17.jpg',
      'assets/img/hopthucphampp/hopthucphampp-16.jpg'
    ],
    catalog: 'hopthucphampp',
    name: 'hopthucphampp'
  },
  {
    images: [
      'assets/img/kyra-pisa/kyra-pisa-8.jpg',
      'assets/img/kyra-pisa/kyra-pisa-9.jpg',
      'assets/img/kyra-pisa/kyra-pisa-4.jpg',
      'assets/img/kyra-pisa/kyra-pisa-5.jpg',
      'assets/img/kyra-pisa/kyra-pisa-7.jpg',
      'assets/img/kyra-pisa/kyra-pisa-6.jpg',
      'assets/img/kyra-pisa/kyra-pisa-2.jpg',
      'assets/img/kyra-pisa/kyra-pisa-3.jpg',
      'assets/img/kyra-pisa/kyra-pisa-1.jpg',
      'assets/img/kyra-pisa/kyra-pisa-10.jpg',
      'assets/img/kyra-pisa/kyra-pisa-11.jpg',
      'assets/img/kyra-pisa/kyra-pisa-12.jpg'
    ],
    catalog: 'kyra-pisa',
    name: 'kyra-pisa'
  },
  {
    images: [
      'assets/img/noithat/noithat-22.jpg',
      'assets/img/noithat/noithat-36.jpg',
      'assets/img/noithat/noithat-23.jpg',
      'assets/img/noithat/noithat-35.jpg',
      'assets/img/noithat/noithat-21.jpg',
      'assets/img/noithat/noithat-20.jpg',
      'assets/img/noithat/noithat-34.jpg',
      'assets/img/noithat/noithat-18.jpg',
      'assets/img/noithat/noithat-30.jpg',
      'assets/img/noithat/noithat-24.jpg',
      'assets/img/noithat/noithat-25.jpg',
      'assets/img/noithat/noithat-31.jpg',
      'assets/img/noithat/noithat-19.jpg',
      'assets/img/noithat/noithat-27.jpg',
      'assets/img/noithat/noithat-33.jpg',
      'assets/img/noithat/noithat-32.jpg',
      'assets/img/noithat/noithat-26.jpg',
      'assets/img/noithat/noithat-9.jpg',
      'assets/img/noithat/noithat-8.jpg',
      'assets/img/noithat/noithat-1.jpg',
      'assets/img/noithat/noithat-3.jpg',
      'assets/img/noithat/noithat-2.jpg',
      'assets/img/noithat/noithat-6.jpg',
      'assets/img/noithat/noithat-7.jpg',
      'assets/img/noithat/noithat-5.jpg',
      'assets/img/noithat/noithat-4.jpg',
      'assets/img/noithat/noithat-17.jpg',
      'assets/img/noithat/noithat-16.jpg',
      'assets/img/noithat/noithat-14.jpg',
      'assets/img/noithat/noithat-28.jpg',
      'assets/img/noithat/noithat-29.jpg',
      'assets/img/noithat/noithat-15.jpg',
      'assets/img/noithat/noithat-11.jpg',
      'assets/img/noithat/noithat-10.jpg',
      'assets/img/noithat/noithat-12.jpg',
      'assets/img/noithat/noithat-13.jpg'
    ],
    catalog: 'noithat',
    name: 'noithat'
  },
  {
    images: [
      'assets/img/congnghiep/congnghiep-6.jpg',
      'assets/img/congnghiep/congnghiep-15.jpg',
      'assets/img/congnghiep/congnghiep-29.jpg',
      'assets/img/congnghiep/congnghiep-28.jpg',
      'assets/img/congnghiep/congnghiep-14.jpg',
      'assets/img/congnghiep/congnghiep-7.jpg',
      'assets/img/congnghiep/congnghiep-5.jpg',
      'assets/img/congnghiep/congnghiep-16.jpg',
      'assets/img/congnghiep/congnghiep-17.jpg',
      'assets/img/congnghiep/congnghiep-4.jpg',
      'assets/img/congnghiep/congnghiep-13.jpg',
      'assets/img/congnghiep/congnghiep-12.jpg',
      'assets/img/congnghiep/congnghiep-1.jpg',
      'assets/img/congnghiep/congnghiep-3.jpg',
      'assets/img/congnghiep/congnghiep-10.jpg',
      'assets/img/congnghiep/congnghiep-11.jpg',
      'assets/img/congnghiep/congnghiep-2.jpg',
      'assets/img/congnghiep/congnghiep-20.jpg',
      'assets/img/congnghiep/congnghiep-21.jpg',
      'assets/img/congnghiep/congnghiep-23.jpg',
      'assets/img/congnghiep/congnghiep-22.jpg',
      'assets/img/congnghiep/congnghiep-9.jpg',
      'assets/img/congnghiep/congnghiep-26.jpg',
      'assets/img/congnghiep/congnghiep-27.jpg',
      'assets/img/congnghiep/congnghiep-8.jpg',
      'assets/img/congnghiep/congnghiep-19.jpg',
      'assets/img/congnghiep/congnghiep-25.jpg',
      'assets/img/congnghiep/congnghiep-30.jpg',
      'assets/img/congnghiep/congnghiep-24.jpg',
      'assets/img/congnghiep/congnghiep-18.jpg'
    ],
    catalog: 'congnghiep',
    name: 'congnghiep'
  },
  {
    images: [
      'assets/img/hupet/hupet-8.jpg',
      'assets/img/hupet/hupet-9.jpg',
      'assets/img/hupet/hupet-12.jpg',
      'assets/img/hupet/hupet-13.jpg',
      'assets/img/hupet/hupet-11.jpg',
      'assets/img/hupet/hupet-10.jpg',
      'assets/img/hupet/hupet-28.jpg',
      'assets/img/hupet/hupet-14.jpg',
      'assets/img/hupet/hupet-15.jpg',
      'assets/img/hupet/hupet-29.jpg',
      'assets/img/hupet/hupet-17.jpg',
      'assets/img/hupet/hupet-16.jpg',
      'assets/img/hupet/hupet-27.jpg',
      'assets/img/hupet/hupet-26.jpg',
      'assets/img/hupet/hupet-24.jpg',
      'assets/img/hupet/hupet-30.jpg',
      'assets/img/hupet/hupet-18.jpg',
      'assets/img/hupet/hupet-19.jpg',
      'assets/img/hupet/hupet-25.jpg',
      'assets/img/hupet/hupet-21.jpg',
      'assets/img/hupet/hupet-20.jpg',
      'assets/img/hupet/hupet-22.jpg',
      'assets/img/hupet/hupet-23.jpg',
      'assets/img/hupet/hupet-4.jpg',
      'assets/img/hupet/hupet-5.jpg',
      'assets/img/hupet/hupet-7.jpg',
      'assets/img/hupet/hupet-6.jpg',
      'assets/img/hupet/hupet-2.jpg',
      'assets/img/hupet/hupet-3.jpg',
      'assets/img/hupet/hupet-1.jpg'
    ],
    catalog: 'hupet',
    name: 'hupet'
  },
  {
    images: [
      'assets/img/line/line-2.jpg',
      'assets/img/line/line-14.jpg',
      'assets/img/line/line-15.jpg',
      'assets/img/line/line-3.jpg',
      'assets/img/line/line-1.jpg',
      'assets/img/line/line-16.jpg',
      'assets/img/line/line-4.jpg',
      'assets/img/line/line-12.jpg',
      'assets/img/line/line-13.jpg',
      'assets/img/line/line-5.jpg',
      'assets/img/line/line-7.jpg',
      'assets/img/line/line-11.jpg',
      'assets/img/line/line-10.jpg',
      'assets/img/line/line-6.jpg',
      'assets/img/line/line-8.jpg',
      'assets/img/line/line-9.jpg'
    ],
    catalog: 'line',
    name: 'line'
  },
  {
    images: [
      'assets/img/giadung/giadung-16.jpg',
      'assets/img/giadung/giadung-1.jpg',
      'assets/img/giadung/giadung-17.jpg',
      'assets/img/giadung/giadung-15.jpg',
      'assets/img/giadung/giadung-29.jpg',
      'assets/img/giadung/giadung-2.jpg',
      'assets/img/giadung/giadung-3.jpg',
      'assets/img/giadung/giadung-28.jpg',
      'assets/img/giadung/giadung-14.jpg',
      'assets/img/giadung/giadung-38.jpg',
      'assets/img/giadung/giadung-10.jpg',
      'assets/img/giadung/giadung-7.jpg',
      'assets/img/giadung/giadung-6.jpg',
      'assets/img/giadung/giadung-11.jpg',
      'assets/img/giadung/giadung-39.jpg',
      'assets/img/giadung/giadung-13.jpg',
      'assets/img/giadung/giadung-4.jpg',
      'assets/img/giadung/giadung-5.jpg',
      'assets/img/giadung/giadung-12.jpg',
      'assets/img/giadung/giadung-61.jpg',
      'assets/img/giadung/giadung-75.jpg',
      'assets/img/giadung/giadung-49.jpg',
      'assets/img/giadung/giadung-48.jpg',
      'assets/img/giadung/giadung-74.jpg',
      'assets/img/giadung/giadung-60.jpg',
      'assets/img/giadung/giadung-76.jpg',
      'assets/img/giadung/giadung-62.jpg',
      'assets/img/giadung/giadung-63.jpg',
      'assets/img/giadung/giadung-77.jpg',
      'assets/img/giadung/giadung-73.jpg',
      'assets/img/giadung/giadung-67.jpg',
      'assets/img/giadung/giadung-66.jpg',
      'assets/img/giadung/giadung-72.jpg',
      'assets/img/giadung/giadung-58.jpg',
      'assets/img/giadung/giadung-64.jpg',
      'assets/img/giadung/giadung-70.jpg',
      'assets/img/giadung/giadung-71.jpg',
      'assets/img/giadung/giadung-65.jpg',
      'assets/img/giadung/giadung-59.jpg',
      'assets/img/giadung/giadung-40.jpg',
      'assets/img/giadung/giadung-54.jpg',
      'assets/img/giadung/giadung-68.jpg',
      'assets/img/giadung/giadung-83.jpg',
      'assets/img/giadung/giadung-82.jpg',
      'assets/img/giadung/giadung-69.jpg',
      'assets/img/giadung/giadung-55.jpg',
      'assets/img/giadung/giadung-41.jpg',
      'assets/img/giadung/giadung-57.jpg',
      'assets/img/giadung/giadung-43.jpg',
      'assets/img/giadung/giadung-80.jpg',
      'assets/img/giadung/giadung-81.jpg',
      'assets/img/giadung/giadung-42.jpg',
      'assets/img/giadung/giadung-56.jpg',
      'assets/img/giadung/giadung-52.jpg',
      'assets/img/giadung/giadung-46.jpg',
      'assets/img/giadung/giadung-85.jpg',
      'assets/img/giadung/giadung-84.jpg',
      'assets/img/giadung/giadung-47.jpg',
      'assets/img/giadung/giadung-53.jpg',
      'assets/img/giadung/giadung-79.jpg',
      'assets/img/giadung/giadung-45.jpg',
      'assets/img/giadung/giadung-51.jpg',
      'assets/img/giadung/giadung-86.jpg',
      'assets/img/giadung/giadung-50.jpg',
      'assets/img/giadung/giadung-44.jpg',
      'assets/img/giadung/giadung-78.jpg',
      'assets/img/giadung/giadung-23.jpg',
      'assets/img/giadung/giadung-37.jpg',
      'assets/img/giadung/giadung-8.jpg',
      'assets/img/giadung/giadung-9.jpg',
      'assets/img/giadung/giadung-36.jpg',
      'assets/img/giadung/giadung-22.jpg',
      'assets/img/giadung/giadung-34.jpg',
      'assets/img/giadung/giadung-20.jpg',
      'assets/img/giadung/giadung-21.jpg',
      'assets/img/giadung/giadung-35.jpg',
      'assets/img/giadung/giadung-19.jpg',
      'assets/img/giadung/giadung-31.jpg',
      'assets/img/giadung/giadung-25.jpg',
      'assets/img/giadung/giadung-24.jpg',
      'assets/img/giadung/giadung-30.jpg',
      'assets/img/giadung/giadung-18.jpg',
      'assets/img/giadung/giadung-26.jpg',
      'assets/img/giadung/giadung-32.jpg',
      'assets/img/giadung/giadung-33.jpg',
      'assets/img/giadung/giadung-27.jpg'
    ],
    catalog: 'giadung',
    name: 'giadung'
  },
  {
    images: [
      'assets/img/hopps/hopps-11.jpg',
      'assets/img/hopps/hopps-10.jpg',
      'assets/img/hopps/hopps-12.jpg',
      'assets/img/hopps/hopps-13.jpg',
      'assets/img/hopps/hopps-16.jpg',
      'assets/img/hopps/hopps-9.jpg',
      'assets/img/hopps/hopps-14.jpg',
      'assets/img/hopps/hopps-15.jpg',
      'assets/img/hopps/hopps-8.jpg',
      'assets/img/hopps/hopps-5.jpg',
      'assets/img/hopps/hopps-4.jpg',
      'assets/img/hopps/hopps-6.jpg',
      'assets/img/hopps/hopps-7.jpg',
      'assets/img/hopps/hopps-3.jpg',
      'assets/img/hopps/hopps-2.jpg',
      'assets/img/hopps/hopps-1.jpg'
    ],
    catalog: 'hopps',
    name: 'hopps'
  },
  {
    images: [
      'assets/img/bohopgaiquaithotron/bohopgaiquaithotron-14.jpg',
      'assets/img/bohopgaiquaithotron/bohopgaiquaithotron-15.jpg',
      'assets/img/bohopgaiquaithotron/bohopgaiquaithotron-8.jpg',
      'assets/img/bohopgaiquaithotron/bohopgaiquaithotron-9.jpg',
      'assets/img/bohopgaiquaithotron/bohopgaiquaithotron-16.jpg',
      'assets/img/bohopgaiquaithotron/bohopgaiquaithotron-12.jpg',
      'assets/img/bohopgaiquaithotron/bohopgaiquaithotron-13.jpg',
      'assets/img/bohopgaiquaithotron/bohopgaiquaithotron-11.jpg',
      'assets/img/bohopgaiquaithotron/bohopgaiquaithotron-10.jpg',
      'assets/img/bohopgaiquaithotron/bohopgaiquaithotron-2.jpg',
      'assets/img/bohopgaiquaithotron/bohopgaiquaithotron-3.jpg',
      'assets/img/bohopgaiquaithotron/bohopgaiquaithotron-1.jpg',
      'assets/img/bohopgaiquaithotron/bohopgaiquaithotron-4.jpg',
      'assets/img/bohopgaiquaithotron/bohopgaiquaithotron-5.jpg',
      'assets/img/bohopgaiquaithotron/bohopgaiquaithotron-7.jpg',
      'assets/img/bohopgaiquaithotron/bohopgaiquaithotron-6.jpg'
    ],
    catalog: 'bohopgaiquaithotron',
    name: 'bohopgaiquaithotron'
  }
];
